### ISSUE TITLE
Rating: please update the song and chart constant database for the japanese version.

### ISSUE THREAD

**Issue by DadangSudadang** [gekichumai/dxrating#108]
New songs and albums are not yet updated for buddies plus. This causes missing songs and wrong chart constant (internal level) for the b50 calculation.

Some charts, such as パーフェクション master (shows as 13.5 but actually 13.4), uses the old constant. The image generation also doesn't show newer songs from buddies plus.

**Comment by GalvinGao** [comment]
Thanks for the feedback! The latest data has been updated and can you please kindly see if they are fixed?

Regarding inaccurate chart constants, to ensure they are as accurate as possible I'm utilizing the data from https://twitter.com/maiLv_Chihooooo to populate the dataset. It seems that for the "パーフェクション Master" chart specifically, constant of such chart in Buddies Plus has not been investigated yet. Whenever the upstream dataset updates the site should reflect it.

**Comment by DadangSudadang** [comment]
Hmm, I was comparing it with another tool and not sure where they get the chart constant data from that is currently missing from the spreadsheet. I'll try asking.

The other calculations are correct now, thanks. Seems like there's an image missing for the image output though:
`"error: ENOENT: no such file or directory, open '/root/dxrating-assets//images/cover/v2/c4c2a77c66fe531962def38cc8d048a3b6ad5fd15bf366d061573ca72e3e5954.jpg'"

**Comment by gekichumai-admin** [comment]
> Hmm, I was comparing it with another tool and not sure where they get the chart constant data from that is currently missing from the spreadsheet. I'll try asking.
> 
> The other calculations are correct now, thanks. Seems like there's an image missing for the image output though: `error: ENOENT: no such file or directory, open '/root/dxrating-assets//images/cover/v2/c4c2a77c66fe531962def38cc8d048a3b6ad5fd15bf366d061573ca72e3e5954.jpg'`

Thanks for the report. We have updated the rendering server resources so this shall be fixed now.

**Comment by DadangSudadang** [comment]
Thank you!
